### ISSUE TITLE
Fewer UI elements are adjusted with minimize to tray on startup

### ISSUE THREAD

**Issue by TheIronWolfModding** [BlueMystical/Dark-Mode-Forms#43] opened 2024-09-04 19:56 UTC
First of all, thank you for your work, very easy to use, and works almost perfectly on a convoluted UI I am modifying.

Currently, the biggest issue is that the app I am trying to change has "minimize to tray" on startup feature.  In form_Load it does:

```
            this.WindowState = FormWindowState.Minimized;
            this.ShowInTaskbar = false;
            this.Hide();
            this.notificationTrayIcon.Visible = true;
```

When I restore app from tray, it is only partially themed.

I tried to call Your constructor after I restore, but it improves only some theming, not all.
```
        this.ShowInTaskbar = true;
            this.notificationTrayIcon.Visible = false;
            this.Show();
 // call your class here.
```
Here are some screenshots.

This is the re-theming without minimize to tray.  Note that some font colors are still not ideal, but pretty close

![image](https://github.com/user-attachments/assets/8e448eb5-04c2-492e-be45-550c98b871f0)

And here's if minimize to tray on startup code is running:
![image](https://github.com/user-attachments/assets/18f48a13-ef4d-4e0f-85b4-8a20df052f01)

Any hints how could I make DM work with minimize to tray on startup?

**Comment by BlueMystical** [comment] 2024-09-04 21:19
i see the groupbox, its probably a glitch with the ForeColor, i'll look into it
We can continue here no problem.

**Comment by BlueMystical** [comment] 2024-09-07 18:04
hi, thanks for the black labels report, i'll make sure to fix them as well.
as for the White Titlebar, i was going to suggest to call this method on the Window_Move event:
```csharp
//Apply Window's Dark Mode to the Form's Title bar:
ApplySystemDarkTheme(OwnerForm, pIsDarkMode);
```
but then i realize the method is private :-(
Thats the one who paints the title and scroll bars
You could copy/paste it somewhere in your own code and call it, its just a couple Win32 Apis
the whole code is here:  https://github.com/BlueMystical/Dark-Mode-Forms/blob/40fa312e792d3234204c0ca03f6fadbbdaee2d72/SourceFiles/DarkModeCS.cs#L896

**Comment by BlueMystical** [comment] 2024-09-09 18:02
just fixed the black labels for disabled controls:

![image](https://github.com/user-attachments/assets/65a518bd-cce0-46b6-989a-06ac50a1bb7b)

Will be up in a few mins.
Sadly i have not still found the cause of the light title bar, but im working on it.

**Comment by BlueMystical** [comment] 2024-09-10 15:12
i just uploaded v1.8.6 in which added the Hide to System Tray on close for the Example Form.
- Closing the Form will send it into the System Tray
- Double Click on the System Tray Icon (the YinYan one) will restore the form

I tried several times with this and the Window paints as it should, no White bar yet.

**Comment by BlueMystical** [comment] 2024-09-15 02:43
hi there!
No those black labels are not intended, darn i tough i fixed them all, oh well..

yes, please send me your app so i can see the titlebar issue.
do you have it on GitHub?

**Comment by BlueMystical** [comment] 2024-09-16 17:49
Hi Wolf,
Thanks for the project, i got it compiling just fine, 
And im getting the darn Black Labels who refuse to take any color but black WTH?  lol
Im on it, i'll let ya know any progress.

Cheers.

**Comment by BlueMystical** [comment] 2024-09-16 18:20
Oh sorry, ill give priority to the title bar issue then

mmmmm.
i took the liberty to modify a litle the Toggle theme replacing the checkboxes for a single button with this code:
```csharp
    private void button1_Click(object sender, EventArgs e)
    {
      this.darkTheme = !this.darkTheme;
      this.darkModeCS.ApplyTheme(this.darkTheme);
      this.view.BackColor = System.Drawing.Color.Black;

      this.config.Write("darkTheme", this.darkTheme ? "1" : "0");
    }
```
and i got this:  22 theme swaps.
https://github.com/user-attachments/assets/459b8899-a682-4eaa-9775-52ca4f07c8a0

**Comment by BlueMystical** [comment] 2024-09-16 18:28
the repro... ?
that was your project
![image](https://github.com/user-attachments/assets/d7aed9ff-56d2-46d8-93d3-90d774df5086)

i only replaced the Theme swapping checkboxes for a single button, to make it easier the multi-clicking

**Comment by BlueMystical** [comment] 2024-09-16 18:30
the issue could be related to the manual setting of the IsDarkMode variable, in my Button code above, i do not touch that variable

**Comment by BlueMystical** [comment] 2024-09-16 18:36
Alright..
dumped my modifications and downloaded your code again, not a single modification
This is what i see:
https://github.com/user-attachments/assets/53fff0fd-c085-4a00-ac42-d8e1c43366aa

**Comment by BlueMystical** [comment] 2024-09-16 18:51
if it helps im on an i9 with 32Gb RAM and an old Geforce GT 730 (good enough only for Minecraft and Youtube xD)

**Comment by BlueMystical** [comment] 2024-09-16 19:17
yes Windows 11, 
and yes i am fixing the black labels, Soon..

**Comment by BlueMystical** [comment] 2024-09-17 18:38
OK, the glitch of Black Labels when they, or their container control is disabled, is now fixed, this was affecting normal single labels, CheckBox Labels and Radio Control Labels.
![image](https://github.com/user-attachments/assets/2942ec0d-be85-40cd-9f53-27c672cb8ca3)

**Comment by BlueMystical** [comment] 2024-09-17 19:07
By the way,
Suggest you to add this code to the Shown event of your Form:

```csharp
    private void MainForm_Shown(object sender, EventArgs e)
    {
      this.darkModeCS.ApplyTheme(this.darkTheme);
    }
```
May help with the Titlebar glitch.

**Comment by BlueMystical** [comment] 2024-09-17 19:21
Nah, dont worry, all is good.

**Comment by BlueMystical** [comment] 2024-09-22 15:23
Thank for reporting this glitches, i'll get to fix them

**Comment by BlueMystical** [comment] 2024-09-23 15:21
@TheIronWolfModding :   Ok, the Combobox highlight is fixed, at least on my initial trials, please test it yourself and let me know:
The fix is just 1 line at line 394 of DarkModeCS.cs

However im having problems to replicate the black label of your first screenshot, what control is that? i assume a Disabled Listbox?

**Comment by BlueMystical** [comment] 2024-09-24 14:39
Great, thanks for letting me know

**Comment by BlueMystical** [comment] 2024-09-24 15:35
The glitch with disabled ComboBoxes is now fixed.
![image](https://github.com/user-attachments/assets/a9a1f364-f73b-44fc-a6b0-d4beb794474c)

**Closed by BlueMystical** 2024-09-24 15:35 UTC

**Comment by BlueMystical** [comment] 2024-09-24 16:43
Nope.
